proxy:
    build: .
    dockerfile: Dockerfile-nginx
    ports:
        - "8888:80"
    links:
        - app
    volumes:
        - /tmp/uploads:/tmp/uploads

app:
    build: .
    dockerfile: Dockerfile-gunicorn
    expose:
        - "5000"
    volumes:
        - /tmp/uploads/:/tmp/uploads
