version: '2'
services:
    proxy:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8888:80"
        links:
            - app
        volumes:
            - /tmp/uploads:/tmp/uploads

    app:
        build:
            context: .
            dockerfile: docker/gunicorn/Dockerfile
        expose:
            - "5000"
        links:
            - redis
        volumes:
            - /tmp/uploads/:/tmp/uploads
        depends_on:
            - redis

    redis:
        image: redis:alpine
        expose:
            - "6379"
